export const LOGIN_REQUEST = "LOGIN_REGISTER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const THEME_MODE_CHANGE = "THEME_MODE_CHANGE";

export const GET_ANNOUNCEMENTS_REQUEST = "GET_ANNOUNCEMENTS_REQUEST";
export const GET_ANNOUNCEMENTS_RESPONSE = "GET_ANNOUNCEMENTS_RESPONSE";

export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_RESPONSE = "GET_NOTIFICATIONS_RESPONSE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_RESPONSE = "GET_ALL_USERS_RESPONSE";
